--- 
javascripts: 
- base: 
  - help
  - jquery.validate
  - jquery
  - controls
  - jquery.form
  - notices
  - jquery.innerfade
  - searches
  - jquery.timeago
  - signup_steps
  - jquery.corner
  - jquery.easing-1.3.pack
  - blog
  - jcarousellite
  - landing
  - _details
  - review_box
  - friends
  - users
  - jquery.pngFix
  - jquery-ui.min
  - dragdrop
  - more_less
  - _conversations
  - signin
  - jquery.form.wizard-2.0.0-RC4
  - add_item_form
  - jquery.scrollTo
  - stream_reply
  - top_bar
  - _essential_search
  - jquery.example
  - jquery.superfish
  - tips
  - jcarousellite_1.0.1.min
  - jquery.colorbox-min
  - anytime
  - video_search
  - jquery.history
  - effects
  - underscore-min
  - jquery.qtip-1.0.0-rc3.min
  - add_event_extra
  - add_place_extra
  - jqueryui
  - facebooker
  - new_message_form
  - labels
  - jquery.hoverIntent
  - jquery.fancybox-1.3.0.pack
  - jquery.equalize-columns
  - jquery.truncator
  - swfobject
  - jquery.truncate-2.3
  - snapshot
  - application
  - admin
  - jquery.min
  - stream
stylesheets: 
- base: 
  - bootstrap_sessions_alerts
  - admin_custom
  - bootstrap
  - site_alerts
  - jquery-ui
  - blog
  - admin_alerts
  - blog_alerts
  - bootstrap_alerts
  - anytime
  - site-information-fancybox
  - jquery.autocomplete
  - site
  - screen
  - jquery.fancybox-1.3.0
  - admin
  - public_alerts
  - all
  - jquery.tooltip
  - public
