# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.
#40d8e645fa3b963c8fc2c088e8f710f9
development:
  api_key: f4a8e66e3e89bbfe4bc733fa0bc76521
  secret_key: 120f3f2d6e45163173c6d4e649bb63c1
  canvas_page_name: hypesample
  callback_url: http://localhost:3000/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

test: &test
  api_key: 7828f141d756a9c8c5454b5f84b85b2e
  secret_key: 04a7df823009222d4469db9badd03533
  canvas_page_name: hypenetworks
  callback_url: http://test.thehypenetworks.com/
  set_asset_host_to_callback_url: true   
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 7828f141d756a9c8c5454b5f84b85b2e
  secret_key: 04a7df823009222d4469db9badd03533
  canvas_page_name: hypenetworks
  callback_url: http://test.thehypenetworks.com/
  set_asset_host_to_callback_url: true   
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

cucumber:
  <<: *test
