development:
  site_url: http://localhost:3000/
  short_url: http://localhost:3000/
  site_name: The Hype

test:
  site_url: http://localhost:3000/
  short_url: http://localhost:3000/
  site_name: The Hype
  
production:
  site_url: http://test.thehypenetworks.com/
  short_url: https://thehy.pe/
  site_name: The Hype