development:
  adapter: mongodb
  host: localhost
  port: 27017
  database: the_hype
  username:
  password:
test: &test
  adapter: mongodb
  host: localhost
  port: 27017
  database: the_hype_test
  username: mongodb
  password:
itg:
  adapter: mongodb
  host: genesis.mongohq.com
  port: 27017
  database: the_hype-itg
  username: squeejee
  password: LetsRoll!
production:
  adapter: mongodb
  host: genesis.mongohq.com
  port: 27017
  database: the_hype-itg
  username: squeejee
  password: LetsRoll!
  
cucumber:
 <<: *test 
